### ISSUE TITLE
παντα τα vars με camelCase 

### ISSUE THREAD

**Issue by tmanolat** [pgourdoupi/spa-employee-next#1]
https://github.com/pgourdoupi/spa-employee-next/blob/c16024d30bf3813d60764dca93908f8b49fc5e73/pages/employees/%5Bid%5D.js#L38

[x, setX]
ποτε να μην κάνεις [X, getX] - είναι ενάντια στην σύμβαση - οι μεταβλητές ξεκινούν με μικρό

κάντο ολούθε

**Comment by pgourdoupi** [comment]
οκ οκ
